# Site settings
title: Ranga Reddy
brief-intro: Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rangareddy.github.io" # the base hostname & protocol for your site
avatar: https://avatars.githubusercontent.com/u/5094273?v=4
timezone: Asia/Kolkata

#permalink: /:year/:month/:day/:title/

permalink: /:title/

# other links
twitter_username: avula_ranga
facebook_username: rangareddy.avula
github_username:  rangareddy
email: rangareddy.avula@gmail.com
linkedIn_username: ranga-reddy-big-data-developer/
stackoverflow: users/1918962/ranga-reddy

description_footer: You can contact me

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname: #rangareddy1988
disqus_shortname: rangareddy1988

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true
    default_lang: plaintext

syntax_highlighter_style: colorful
markdown_ext: markdown,mkdown,mkdn,mkd,md

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

include:
  - _data

exclude:
  - _drafts
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock